// User-facing text for the install feature, centralized (see AGENTS.md) — no literal
// strings in InstallScreen.tsx JSX.
export const INSTALL_STRINGS = {
  headerTitle: 'Nouvelle installation',
  help: 'Aide',
  resumedTitle: "Installation reprise là où tu t'étais arrêté",
  resumedRestart: 'Recommencer',
  step1: {
    caption: "Vise l'étiquette sous la batterie",
    manualButton: 'Saisir à la main',
    manualLabel: 'Numéro de série',
    placeholder: 'RV-1234-5678',
    invalidFormat: 'Format attendu : RV-1234-5678',
    cameraUnavailable: 'Caméra indisponible : saisis le numéro',
    scanInvalid: 'Code illisible : réessaie ou saisis le numéro à la main.',
    serialLabel: (serial: string) => `N° ${serial}`,
  },
  step2: {
    modeNew: 'Nouveau client',
    modeExisting: 'Client existant',
    searchPlaceholder: 'Rechercher un client…',
    searchEmpty: 'Aucun client trouvé',
    nameLabel: 'Nom',
    addressLabel: 'Adresse',
    phoneLabel: 'Téléphone',
    emailLabel: 'Email',
    required: 'Obligatoire',
    optional: 'Facultatif',
    emailHint: 'pour inviter ton client dans son app',
    namePlaceholder: 'Nom du client',
    phonePlaceholder: '06 …',
    emailPlaceholder: 'nom@exemple.fr',
    gpsHint: '📍 Position du téléphone · modifiable',
    useLocation: 'Utiliser ma position',
    invalidEmail: 'Email invalide',
  },
  step3: {
    autoconsommation: {
      title: 'Autoconsommation',
      description: 'Stocke le surplus solaire pour le soir. Le standard.',
    },
    secours: {
      title: 'Secours prioritaire',
      description: 'Garde toujours 30 % pour les coupures.',
    },
    heures_creuses: {
      title: 'Heures creuses',
      description: 'Recharge aussi la nuit au tarif heures creuses.',
    },
  },
  step4: {
    runningTitle: 'Test en cours…',
    runningDetail: 'La batterie envoie ses premières données.',
    skip: 'Passer, vérifier plus tard',
    successLabel: (socPct: number) => `✓ La batterie communique · charge ${socPct} %`,
    failTitle: 'La batterie ne répond pas encore',
    retry: 'Réessayer',
    skippedMention: 'Une manip « Vérifier la communication » sera créée',
  },
  step5: {
    created: 'Ce qui sera créé',
    later: 'À compléter plus tard depuis le système',
    batteryRow: (label: string, serial: string) => `Batterie ${label} · N° ${serial}`,
    clientRow: (name: string, address: string) => `Client ${name}, ${address}`,
    modeRow: (label: string) => `Mode ${label}`,
    commRow: (verified: boolean) =>
      `Communication : ${verified ? 'Vérifiée' : 'À vérifier plus tard'}`,
    phone: 'Téléphone',
    email: 'Email',
    pvPower: 'Puissance crête PV',
    inverterBrand: "Marque d'onduleur",
    boardPhotos: 'Photos du tableau',
  },
  success: {
    title: 'Installation créée ✓',
    subtitle: (client: string, city: string) => `${client} · ${city} apparaît en tête de ton parc`,
    offline: 'Enregistrée · envoi au retour du réseau',
    home: "Retour à l'accueil",
    viewSystem: 'Voir le système',
  },
} as const;
