// All user-facing text for the closure screen (spec §3.4 D, maquette Cloture.dc.html).
export const CLOSURE_STRINGS = {
  notFoundTitle: "Cette manip n'existe plus",
  arrivedAt: (hhmm: string) => `Arrivé à ${hhmm}`,
  resultTitle: 'Résultat',
  resolved: 'Résolu',
  notResolved: 'Pas résolu',
  whatIDid: "Ce que j'ai fait",
  otherChip: 'Autre',
  otherAction: 'Autre',
  photos: 'Photos',
  addPhoto: 'Ajouter une photo',
  photoLabel: (index: number) => `Photo ${index}`,
  note: 'Note (facultatif)',
  dictate: 'Dicter',
  listening: 'Écoute…',
  audioMemoNote: 'Mémo audio joint (transcription impossible hors ligne)',
  nextTitle: 'Et maintenant ?',
  repasser: 'Je repasse',
  repasserDetail: 'Nouvelle échéance : demain',
  transmettre: 'Je transmets à Revolty',
  transmettreDetail: 'Revolty reprend la main et te tient au courant',
  closeCta: 'Clôturer',
  closedOnline: 'Clôturée ✓',
  closedOffline: 'Enregistrée · envoi au retour du réseau',
  waitingBattery: 'En attente de confirmation par la batterie…',
  confirmedBattery: 'Confirmé par la batterie ✓',
  recapRepasser: 'Tu repasses demain',
  recapTransmettre: 'Transmise à Revolty',
  backHome: 'Retour à l’accueil',
  viewSystem: 'Voir le système',
} as const;
